server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location = / {
        try_files /views/home/index.html =404;
    }

    location / {
        try_files $uri $uri/ /views$uri/index.html /views$uri.html =404;
    }
}