server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # 1. Halaman Utama (/)
    location = / {
        try_files /views/home/index.html =404;
    }

    # 2. Khusus Folder Assets (Tolak fallback ke HTML, return 404 jika file JS/CSS tidak ada)
    location /assets/ {
        try_files $uri =404;
    }

    # 3. Dynamic Routes Halaman Web (seperti /glossary/)
    location / {
        try_files $uri $uri/ /views$uri/index.html /views$uri.html =404;
    }
}