server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # 1. Folder Assets dijadikan PUBLIC (Langsung disajikan tanpa fallback/redirect)
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
    }

    # 2. Halaman Utama (/) mengarah ke views/home/index.html
    location = / {
        try_files /views/home/index.html =404;
    }

    # 3. Route Halaman Web (seperti /glossary/ -> views/glossary/index.html)
    location / {
        try_files $uri $uri/ /views$uri/index.html /views$uri.html =404;
    }
}